### ISSUE TITLE
line 36 (ü) in endings.js

### ISSUE THREAD

**Issue by kkarimi** [ericnishio/pinyinize.js#2]
This line currently throws exception in chrome:

<img width="871" alt="screen shot 2015-08-29 at 23 09 14" src="https://cloud.githubusercontent.com/assets/875218/9564560/1320ecfc-4ea3-11e5-8393-26ddc2baa126.png">

Not sure what would be a good solution but thought I should let you know.

**Comment by ericnishio** [comment]
I was unable to reproduce the error, but I've pushed a possible fix (3.3.1).
